backend:
  name: github
  branch: master
  repo: JacobDFrank/tawGatsby2-rearchitecture

media_folder: static/images/uploads
public_folder: /images/uploads
logo_url: https://taw-org-staging.netlify.com/images/TAW-Brand-Logo19.svg


collections:
  - name: 'content'
    label: 'Pages'
    files:
      - label: 'Home Page'
        name: 'Home'
        file: 'src/content/Home.md'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: string}
          - {label: subIntro, name: subIntro, widget: markdown}
  - name: 'team'
    label: 'Team'
    label_singular: 'Team Member'
    folder: 'src/team'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Team Member', name: 'title', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: 'src/projects'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'File Name', name: 'URLpath', widget: 'string', pattern: ['^\/[/.a-zA-Z0-9-]+$', 'Must start with a forward slash and not contain special characters besides: /, .,  -']}
      - { label: 'Project Title', name: 'title', widget: 'string' }
      - { label: 'Publish project?', name: 'published', widget: 'boolean' }
      - { label: 'Publish Date', hint: 'Projects will be listed in descending order based on date', name: 'date', widget: 'date', default: '2019-01-01', format: 'MMMM DD, YYYY'}
      - { label: 'Project Description', name: 'title', widget: 'string', pattern: ['^.{1,85}$', 'Must have no more than 85 characters']}
      - { label: 'Project Tags', name: 'tags', widget: 'string', pattern: ['^.{1,44}$', 'Must have no more than 44 characters']}
      - { label: 'Time Period', hint: 'Ex: Summer 2017 or Annually, Completed Each Fall', name: 'timePeriod', widget: 'string', pattern: ['^.{1,32}$', 'Must have no more than 32 characters']}
      - { label: 'Project Case Study', hint: 'Write about it, you can do it in markdown', name: 'body', widget: 'markdown'}
  - name: 'speakers2018'
    label: 'Speakers 2018'
    label_singular: 'Speaker'
    folder: 'src/2018/speakers'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Speaker Name', name: 'title', widget: 'string' }
      - { label: 'Job Title', name: 'jobTitle', widget: 'string', pattern: ['^.{1,80}$', 'Must have no more than 80 characters']}
      - { label: 'Website/Company Link', name: 'links', widget: 'string', hint: 'Ex: https://laurenoneilldesign.com/ or http://localprojects.com'}
      - {label: 'Headshot', name: 'headshot', widget: 'image', default: '', media_library:, config:, multiple: false}
      - label: 'Talks'
        name: 'talks'
        widget: 'list'
        required: false
        fields:
          - {label: 'Talk(Team test)', name: 'talk', widget: 'relation', collection: 'team', searchFields: ['title'], valueField: 'title', displayFields: ['title', 'bio']}